### PR TITLE
Assignment 4.2

### LINKED ISSUE #18: dockering the python package

### PR DESCRIPTION
**Pull request by janakiguggilla**
https://hub.docker.com/repository/docker/janakiguggilla/housing_price/general ---> this is the dockerhub link and submitting the recording session in another branch

### CODE REVIEW

**Comment by janakiguggilla** [comment]
docker recording is present in docker_recording branch, please review it

**Comment by Amulya2110** [comment]
Please upload the Dockerfile you have the used

**Comment by janakiguggilla** [comment]
hii amulya, where should I upload dockerfile?, like in the branch or in the comments here

**Comment by Amulya2110** [comment]
You can upload it as a part of code repo itself

**Comment by janakiguggilla** [comment]
it is already present in housing_price_package/dist/Dockerfile path , should I have to upload outside this folder or this is fine

**Review by Amulya2110 — APPROVED** [review]

**Pull request merged**
