### PR TITLE
Enh/2/test

### PR DESCRIPTION
**Pull request by janakiguggilla**
screenshot of output of housing data

### CODE REVIEW

**Review by Amulya2110 — CHANGES_REQUESTED** [review]
CODE - The code structuring format is wrong , you have created a new branch out of master and have a nonstandard code folder, It should not be like that , there should be only one README.md, and nonstandardcode.py should not be inside the folder.
The env.yml looks little different , can you let me know how you have created that?

**Comment by janakiguggilla** [comment]
> CODE - The code structuring format is wrong , you have created a new branch out of master and have a nonstandard code folder, It should not be like that , there should be only one README.md, and nonstandardcode.py should not be inside the folder. The env.yml looks little different , can you let me know how you have created that?

@Amulya2110  I used conda env create -f env.yml command, but I forgot to remove the prefix

**Review by Amulya2110 — CHANGES_REQUESTED** [review]
Can you change the code format ?
CODE - The code structuring format is wrong , you have created a new branch out of master and have a nonstandard code folder, It should not be like that , there should be only one README.md, and nonstandardcode.py should not be inside the folder.

**Comment by janakiguggilla** [comment]
> Can you change the code format ? CODE - The code structuring format is wrong , you have created a new branch out of master and have a nonstandard code folder, It should not be like that , there should be only one README.md, and nonstandardcode.py should not be inside the folder.

Yes Amulya, I will change it and will request for PR once done

**Comment by janakiguggilla** [comment]
image

made the suggested changes, please review it

**Comment by Amulya2110** [comment]
DOC - In the readme you have written how one can create env.yml , instead can you write the command for how one can replicate this environment using the env,yml file which is present

**Comment by janakiguggilla** [comment]
> DOC - In the readme you have written how one can create env.yml , instead can you write the command for how one can replicate this environment using the env,yml file which is present

Updated the required changes, please review it.

**Review by Amulya2110 — APPROVED** [review]

**Pull request merged**
